
DROP TABLE user IF EXISTS;
CREATE TABLE user (
  id	INTEGER GENERATED BY DEFAULT AS IDENTITY,
  name	VARCHAR(60),
  password  VARCHAR(30), 
  email	VARCHAR(60), 
  image VARCHAR(60)
);
CREATE INDEX user_name ON user (name);

-- ---------------

DROP TABLE roles IF EXISTS;
CREATE TABLE roles (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY,
	role_name VARCHAR(255)
);

DROP TABLE user_roles IF EXISTS;
CREATE TABLE user_roles (
	uid INTEGER NOT NULL, 
	rid INTEGER NOT NULL, 
	constraint user_roles_uq UNIQUE (uid, rid)
);

DROP TABLE permissions IF EXISTS;
CREATE TABLE permissions (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY,
	permission VARCHAR(255)
);

DROP TABLE roles_permissions IF EXISTS;
CREATE TABLE roles_permissions (
	rid INTEGER NOT NULL, 
	pid INTEGER NOT NULL, 
	constraint roles_permission_uq UNIQUE (rid, pid)
);
